UserManagement/Controllers/AddressController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UserManagement.Data.Models;
using UserManagement.Repositories;
using X.PagedList;

namespace UserManagement.Controllers
{
    public class AddressController : Controller
    {
        Context c = new Context();
        AddressRepository addressRepository = new AddressRepository();
        public IActionResult Index(int page = 1)
        {            
            return View(addressRepository.ListT("User").ToPagedList(page, 5));
        }

        [HttpGet]
        public IActionResult AddAddress()
        {
            List<SelectListItem> values = (from x in c.Users.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Username,
                                               Value = x.UserId.ToString()
                                           }).ToList();
            ViewBag.v1 = values;
            return View();
        }

        [HttpPost]
        public IActionResult AddAddress(Address p)
        {
            if (!ModelState.IsValid)
            {
                return View("AddAddress");
            }
            addressRepository.AddT(p);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteAddress(int id)
        {
            addressRepository.DeleteT(new Address {AddressId = id});
            return RedirectToAction("Index");
        }

        public IActionResult GetAddress(int id)
        {
            var x = addressRepository.GetT(id);
            List<SelectListItem> values = (from y in c.Users.ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.Username,
                                               Value = y.UserId.ToString()
                                           }).ToList();
            ViewBag.v1 = values;            
            Address a = new Address()
            {
                AddressId = x.AddressId,
                Name = x.Name,
                City = x.City,
                County = x.County,
                Neighbourhood = x.Neighbourhood,
                LongAddress = x.LongAddress,
                UserId = x.UserId
            };
            return View(a);
        }

        [HttpPost]
        public IActionResult UpdateAddress(Address p)
        {
            var x = addressRepository.GetT(p.AddressId);
            x.Name = p.Name;
            x.City = p.City;
            x.County = p.County;
            x.Neighbourhood = p.Neighbourhood;
            x.LongAddress = p.LongAddress;
            x.UserId = p.UserId;
            addressRepository.UpdateT(x);
            return RedirectToAction("Index");
        }
    }
}

UserManagement/Controllers/LoginController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UserManagement.Data.Models;

namespace UserManagement.Controllers
{    
    public class LoginController : Controller
    {
        Context c = new Context();

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Index(Admin p)
        {
            var dataValue = c.Admins.FirstOrDefault(x => x.Username == p.Username && x.Password == p.Password);
            if(dataValue != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, p.Username)
                };
                var userIdentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index", "User");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Login");
        }
    }
}

UserManagement/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using UserManagement.Data.Models;
using Token = UserManagement.Data.Models.Token;

namespace UserManagement.Controllers
{
    public class ProductController : Controller
    {
        string Baseurl = "http://185.124.86.45:8899";
        string TokenUrl = "http://185.124.86.45:8899/token";

        public async Task<IActionResult> Index()
        {
            List<Product> products = new List<Product>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();

                var loginData = new Dictionary<string, string>
        {
            {"username", "*******"},
            {"password", "********"},
            {"grant_type", "password"}
        };

                HttpResponseMessage TokenResponse = await client.PostAsync(TokenUrl, new FormUrlEncodedContent(loginData));

                var tokenResponce = TokenResponse.Content.ReadAsStringAsync().Result;
                var token = JsonConvert.DeserializeObject<Token>(tokenResponce);

                string queryParams = "/api/Integration//EticaretStokListesi?tarih=1900-01-01&depoid=1&miktarsifirdanbuyukstoklarlistelensin=False";

                var fullUrl = Baseurl + queryParams;
                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.AccessToken);

                HttpResponseMessage Res = await client.GetAsync(fullUrl);

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    var productsRaw = JsonConvert.DeserializeObject<dynamic>(EmpResponse);
                    products = JsonConvert.DeserializeObject<List<Product>>(productsRaw);
                }
                return View(products);
            }
        }
    }
}

UserManagement/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using UserManagement.Repositories;
using UserManagement.Data.Models;
using X.PagedList;

namespace UserManagement.Controllers
{
    public class UserController : Controller
    {
        UserRepository userRepository = new UserRepository();
        public IActionResult Index(int page = 1)
        {           
            return View(userRepository.ListT().ToPagedList(page, 5));
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddUser(User p)
        {
            if(!ModelState.IsValid)
            {
                return View("AddUser");
            }
            userRepository.AddT(p);
            return RedirectToAction("Index");
        }

        public IActionResult GetUser(int id)
        {
            var x = userRepository.GetT(id);
            User user = new User()
            {
                Username = x.Username,
                Name = x.Name,
                Lastname = x.Lastname,
                Email = x.Email,
                Password = x.Password,
                UserId = x.UserId
            };
            return View(user);
        }

        [HttpPost]
        public IActionResult UpdateUser(User p)
        {
            var x = userRepository.GetT(p.UserId);
            x.Username = p.Username;
            x.Name = p.Name;
            x.Lastname = p.Lastname;
            x.Email = p.Email;
            x.Password = p.Password;
            userRepository.UpdateT(x);
            return RedirectToAction("Index");
        }
    }
}

UserManagement/Views/Address/AddAddress.cshtml
@model UserManagement.Data.Models.Address

@{
    ViewData["Title"] = "AddAddress";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Address</h2>
<br />
@using (Html.BeginForm("AddAddress", "Address", FormMethod.Post))
{
    @Html.Label("Name:")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
    <br />
    @Html.Label("City:")
    @Html.TextBoxFor(x => x.City, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.City, "", new { @style = "color:red" })
    <br />
    @Html.Label("County:")
    @Html.TextBoxFor(x => x.County, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.County, "", new { @style = "color:red" })
    <br />
    @Html.Label("Neighbourhood:")
    @Html.TextBoxFor(x => x.Neighbourhood, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Neighbourhood, "", new { @style = "color:red" })
    <br />
    @Html.Label("Long Address:")
    @Html.TextAreaFor(x => x.LongAddress, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.LongAddress, "", new { @style = "color:red" })
    <br />
    @Html.Label("Username:")
    @Html.DropDownListFor(x=>x.UserId,(List<SelectListItem>)ViewBag.v1, new { @class="form-control"})
    <br />
    <button class="btn btn-primary">Create</button>
}

UserManagement/Views/Address/GetAddress.cshtml
@model UserManagement.Data.Models.Address

@{
    ViewData["Title"] = "GetAddress";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update Address</h2>
<br />
@using (Html.BeginForm("UpdateAddress", "Address", FormMethod.Post))
{
    @Html.Label("Address Id:")
    @Html.TextBoxFor(x => x.AddressId, new { @class = "form-control", @readonly = "readonly" });
    <br />
    @Html.Label("Name:")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
    <br />
    @Html.Label("City:")
    @Html.TextBoxFor(x => x.City, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.City, "", new { @style = "color:red" })
    <br />
    @Html.Label("County:")
    @Html.TextBoxFor(x => x.County, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.County, "", new { @style = "color:red" })
    <br />
    @Html.Label("Neighbourhood:")
    @Html.TextBoxFor(x => x.Neighbourhood, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Neighbourhood, "", new { @style = "color:red" })
    <br />
    @Html.Label("Long Address:")
    @Html.TextAreaFor(x => x.LongAddress, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.LongAddress, "", new { @style = "color:red" })
    <br />
    @Html.Label("Username:")
    @Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Update</button>
}

UserManagement/Views/Address/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@model IPagedList<UserManagement.Data.Models.Address>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Address List</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Address ID</th>
        <th>Name</th>
        <th>City</th>
        <th>County</th>
        <th>Neighbourhood</th>
        <th>Long Address</th>
        <th>Username</th>
        <th>Actions</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <th>@x.AddressId</th>
            <td>@x.Name</td>
            <td>@x.City</td>
            <td>@x.County</td>
            <td>@x.Neighbourhood</td>
            <td>@x.LongAddress</td>
            <td>@x.User.Username</td>
            <td>
                <a href="/Address/DeleteAddress/@x.AddressId" class="btn btn-danger">Delete</a>
                <a href="/Address/GetAddress/@x.AddressId" class="btn btn-success">Update</a>
            </td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
<a href="/Address/AddAddress" class="btn btn-primary">Add Address</a>

UserManagement/Views/Login/Index.cshtml
@model UserManagement.Data.Models.User

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .login-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }

            .login-container h2 {
                text-align: center;
                margin-bottom: 20px;
            }

            .login-container input[type="text"],
            .login-container input[type="password"] {
                width: 100%;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #ccc;
                border-radius: 3px;
                box-sizing: border-box;
            }

            .login-container input[type="submit"] {
                width: 100%;
                padding: 10px;
                border: none;
                background-color: #007bff;
                color: #fff;
                cursor: pointer;
                border-radius: 3px;
                box-sizing: border-box;
            }

                .login-container input[type="submit"]:hover {
                    background-color: #0056b3;
                }
    </style>
</head>
<body>
    <div class="login-container">
        <h2>Login Form</h2>
        <form id="login-form" action="/Login/Index" method="post">
            <label for="Username">Username:</label>
            <input type="text" name="Username" placeholder="Enter your username" required="" maxlength="20">
            <label for="Password">Password:</label>
            <input type="password" name="Password" placeholder="Enter your password" required="" maxlength="20">
            <br />
            <input type="submit" value="Login">
        </form>
    </div>
</body>
</html>

UserManagement/Views/Product/Index.cshtml
@model List<UserManagement.Data.Models.Product>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="productTable" class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Product Code</th>
            <th>Product Name</th>
            <th>VAT Rate</th>
            <th>Discounted Amount</th>
            <th>Amount</th>
            <th>Inventory</th>
            <th>Manufacturer Company Name</th>
            <th>n11</th>
            <th>ggidiyor</th>
            <th>getir</th>
            <th>trendyol Marketplace</th>
            <th>pazarama Marketplace</th>
            <th>hepsiburada</th>
            <th>trendyol</th>
            <th>amazon</th>
            <th>eptt</th>
            <th>Date of Update</th>
            <th>Product Description</th>
            <th>Images</th>
            <th>Barcodes</th>
            <th>Groups</th>
            <th>Category</th>
            <th>Display in E-commerce</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.ID</td>
                <td>@product.UrunKodu</td>
                <td>@product.UrunAdi</td>
                <td>@product.KDVOrani</td>
                <td>@product.IndirimliTutar</td>
                <td>@product.Tutar</td>
                <td>@product.Envanter</td>
                <td>@product.UreticiFirmaAdi</td>
                <td>@product.n11</td>
                <td>@product.ggidiyor</td>
                <td>@product.getir</td>
                <td>@product.trendyol_marketplace</td>
                <td>@product.pazarama_marketplace</td>
                <td>@product.hepsiburada</td>
                <td>@product.trendyol</td>
                <td>@product.amazon</td>
                <td>@product.eptt</td>
                <td>@product.GuncellemeTarihi</td>
                <td>@Html.Raw(@product.UrunAciklamasi)</td>
                <td>
                    @foreach (var resim in product.Resimler)
                    {
                        <img src="@resim" alt="Resim" class="img-thumbnail" />
                    }
                </td>
                <td>
                    @foreach (var barkod in product.Barkodlar)
                    {
                        <div>
                            Barkod: @barkod.Barkodu<br />
                            Birim: @barkod.Birim<br />
                            Fiyat: @barkod.Fiyat
                        </div>
                    }
                </td>
                <td>
                    @foreach (var grup in product.Gruplar)
                    {
                        <div>@grup</div>
                    }
                </td>
                <td>@product.Kategori</td>
                <td>@product.EticaretteGoruntulensin</td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.dataTables.css" />

    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('#productTable').DataTable();
        });
    </script>
}

UserManagement/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/User/Index/">UserManagement</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="/User/Index">User</a></li>
                <li><a href="/Address/Index">Address</a></li>
                <li><a href="/Product/Index">Product List</a></li>
                <li><a href="/Login/Logout">Logout</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

UserManagement/Views/User/AddUser.cshtml
@model UserManagement.Data.Models.User

@{
    ViewData["Title"] = "AddUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create User</h2>
<br />
@using (Html.BeginForm("AddUser", "User", FormMethod.Post))
{
    @Html.Label("Username:")
    @Html.TextBoxFor(x => x.Username, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Username, "", new { @style = "color:red" })
    <br />
    @Html.Label("Name:")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
    <br />
    @Html.Label("Lastname:")
    @Html.TextBoxFor(x => x.Lastname, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Lastname, "", new { @style = "color:red" })
    <br />
    @Html.Label("E-Mail:")
    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Email, "", new { @style = "color:red" })
    <br />
    @Html.Label("Password:")
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control", Type = "password" });
    @Html.ValidationMessageFor(x => x.Password, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-primary">Create</button>
}

UserManagement/Views/User/GetUser.cshtml
@model UserManagement.Data.Models.User

@{
    ViewData["Title"] = "GetUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update User</h2>
<br />
@using (Html.BeginForm("UpdateUser", "User", FormMethod.Post))
{
    @Html.Label("User Id:")
    @Html.TextBoxFor(x => x.UserId, new { @class = "form-control", @readonly = "readonly" });
    <br />
    @Html.Label("Username:")
    @Html.TextBoxFor(x => x.Username, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Username, "", new { @style = "color:red" })
    <br />
    @Html.Label("Name:")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
    <br />
    @Html.Label("Lastname:")
    @Html.TextBoxFor(x => x.Lastname, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Lastname, "", new { @style = "color:red" })
    <br />
    @Html.Label("E-Mail:")
    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" });
    @Html.ValidationMessageFor(x => x.Email, "", new { @style = "color:red" })
    <br />
    @Html.Label("Password:")
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control", Type = "password" });
    @Html.ValidationMessageFor(x => x.Password, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-primary">Update</button>
}

UserManagement/Views/User/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@model IPagedList<UserManagement.Data.Models.User>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User List</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>User ID</th>
        <th>Username</th>
        <th>Name</th>
        <th>Lastname</th>
        <th>E-Mail</th>
        <th>Password</th>
        <th>Actions</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <th>@x.UserId</th>
            <td>@x.Username</td>
            <td>@x.Name</td>
            <td>@x.Lastname</td>
            <td>@x.Email</td>
            <td>@x.Password</td>
            <td>
                <a href="/User/GetUser/@x.UserId" class="btn btn-success">Update</a>
            </td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
<a href="/User/AddUser/" class="btn btn-primary">Add User</a>